### ISSUE TITLE
Request: "Report Status" command (5-5)

### ISSUE THREAD

**Issue by michaelruigrok** [Asaayu/integrated-voice-control-system#1]
I end up using this one frequently to update squad casualties in singleplayer.

Aliases would be 'sitrep', 'report in'

I suppose that other `5` commands _may_ be useful, like "Injured" in the command menu automatically assigns your squad medic to heal you. "Call Support" (5-1) would be great, but I'm not sure if that's functional anywhere in base content.

**Comment by Asaayu** [comment]
I didn't add these originally since I these are handled internally by the engine. I can have it reproduce the report status command, but it won't be exactly like how the 5-5 version works.

**Comment by Asaayu** [comment]
Status commands will be available in version 1.0.16.0

**Comment by Asaayu** [comment]
Should be available now
