### ISSUE TITLE
Function Request: Watch position

### ISSUE THREAD

**Issue by ampersand38** [Asaayu/integrated-voice-control-system#4]
**Is this a new function or phrase**
Both.

**Please describe your request in detail**
Command units to watch the position under the cursor, in the 3D world or on map. 

**Additional context**
Vanilla keybind is Command > Command Watch

**Comment by Ethan-Johnson-NZ** [comment]
I've added a new "Watch There"/"Watch Here" command that will get the AI to watch a position
