### ISSUE TITLE
Function Request: Move to me / my position

### ISSUE THREAD

**Issue by ampersand38** [Asaayu/integrated-voice-control-system#6]
**Is this a new function or phrase**
Both.

**Please describe your request in detail**
In buildings and urban areas it can be difficult to get ai to exactly the right spot, especially in higher floors.
It would be great to be able to order AI to move to exactly where the player is.
`_unit doMove ASLtoATL getPosASL player`

Potential phrases:
"take my position"
"move to my spot"

**Comment by Asaayu** [comment]
I've added the commands in v2.0.0
